### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bitcometz** [rsemeraro/PyPore#1]
hello,
I try to install PyPore without Root authority on our linux cluster and the following error message was encountered:
[20/22] Cythonizing /tmp/easy_install-1Rxpzk/h5py-2.9.0/h5py/h5t.pyx
[21/22] Cythonizing /tmp/easy_install-1Rxpzk/h5py-2.9.0/h5py/h5z.pyx
[22/22] Cythonizing /tmp/easy_install-1Rxpzk/h5py-2.9.0/h5py/utils.pyx

/tmp/easy_install-1Rxpzk/h5py-2.9.0/h5py/api_compat.h:27:18: error：hdf5.h：no such file or dierectory
/tmp/easy_install-1Rxpzk/h5py-2.9.0/h5py/defs.c:476:23: error：H5Cpublic.h：no such file or dierectory
/tmp/easy_install-1Rxpzk/h5py-2.9.0/h5py/defs.c:477:21: error：hdf5_hl.h：no such file or dierectory
...

Thanks

Best

**Comment by rsemeraro** [comment]
Hello,
is the hdf5 library installed on your machine?
You can check this by typing  `h5cc -showconfig`.  You'll get a screen like this.
![Screen Shot 2019-04-19 at 09 11 07](https://user-images.githubusercontent.com/7014000/56411862-7afa3800-6282-11e9-896b-d24a2ed9b9e9.png)
If missing, you have to install the hdf5 library by means of your packages installer (`sudo apt-get install libhdf5-dev`). 
Alternatively, if you have a conda distribution, you can get it by typing `conda install -c anaconda hdf5`.

**Comment by bitcometz** [comment]
Thanks! Since I did not have the root authority. So I find another way to solve this problem. I used conda to install all the Dependencies. So when I run "python setup.py install" and I do not need to the do the installation again. Anyway, I run PyPore successfully on the "test_dataset" and PyPore generate the files "Test_pore_activity_map.html" and "Test_sequencing_summary.html".

However, I did not get the right results from the files generated by Guppy(Version 2.0.10) with PromethION.
Usually, guppy generate the following files:

fast5_skip/                        sequencing_summary/
fast5_fail/                        fastq_fail/
fast5_pass/                        fastq_pass/

So, I build the tmp directory "test_in" and link the original directory "fast5_fail" and "fast5_pass" to "fail" and "pass", just like those in the "test_dataset" and then I run PyPore:
...
[PyPore][WARNING] - Channel 504 inactive!
[PyPore][WARNING] - Channel 505 inactive!
[PyPore][WARNING] - Channel 506 inactive!
[PyPore][WARNING] - Channel 507 inactive!
[PyPore][WARNING] - Channel 508 inactive!
[PyPore][WARNING] - Channel 509 inactive!
[PyPore][WARNING] - Channel 510 inactive!
[PyPore][WARNING] - Channel 511 inactive!
[PyPore][INFO] - Plotting results...

Traceback (most recent call last):
  File "dir/pypore/bin/pypore", line 11, in <module>
    load_entry_point('PyPore==0.1', 'console_scripts', 'pypore')()
  File "dir/pypore/lib/python2.7/site-packages/PyPore-0.1-py2.7.egg/lib/pypore.py", line 61, in main
    run_subtool(mod, ags, parser)
  File "dir/envs/pypore/lib/python2.7/site-packages/PyPore-0.1-py2.7.egg/lib/pypore.py", line 16, in run_subtool
    sq.run(ags)
  File "dir/pypore/lib/python2.7/site-packages/PyPore-0.1-py2.7.egg/lib/seqstats.py", line 125, in run
    ArgsReader(args)
  File "dir/envs/pypore/lib/python2.7/site-packages/PyPore-0.1-py2.7.egg/lib/seqstats.py", line 52, in ArgsReader
    sq.run(ags)
...

It did generate the *_activity_map.html but all the channels are empty.
Do PyPore support the data generated from Guppy? Or it required specific names format of the data?

Thanks

best

**Comment by rsemeraro** [comment]
I never worked with PromethION data. However, i suppose it produces a multi-read fast5 dataset. If i'm right, you can try to activate the multi-read flag via the `--multi_read_fast5 yes` command.
